### ISSUE TITLE
Small issues

### ISSUE THREAD

**Issue by santiagobasulto** [rmotr/rmotr-sis#7]
- [x] Simplify user/profile structure.
- [x] Add title to assignments.
- [x] More info for assignment attempts (n attempts). Status (solved, pending).
- [ ] Save assignment attempt as the student sent it (without a footer).
- [x] Make `students` nullable in a course instance
- [x] Fix urls
- [x] Manytomany relationship between Assignment and Lecture.
- [x] Show to the teacher in the assignments summary which student attempted to solve an assignment but couldn't complete it. (with an error cross).

**TODO**: Add data to lecture (mandatory readings, optional readings, group assignments, etc)

```
tried_to_resolved = AssignmentAttempt.exclude(user=student, lecture=lecture, end_date=None).exists()
```
